---
deployment:
  tasks:
    - export DEPLOYPATH=/home/jvxkczxshosting/public_html/attendance/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R account $DEPLOYPATH
