---
deployment:
  tasks:
    - export DEPLOYPATH=/home/jvxkczxshosting/public_html/attendance/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp -rf assets $DEPLOYPATH
    - /bin/cp -rf accounts $DEPLOYPATH
